name: Automated.Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: msbuild K2XML_Converter.sln -p:Configuration=Release
